[versions]
kotlin = "1.9.22"
zxing = "3.5.3"
junit = "5.10.1"

[libraries]
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxing" }
zxing-se = { group = "com.google.zxing", name = "javase", version.ref = "zxing" }

kotlin-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit5", version.ref = "kotlin" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version = "1.10.1" }
assertk = { group = "com.willowtreeapps.assertk", name = "assertk", version = "0.28.0" }

miglayout = { group = "com.miglayout", name = "miglayout-swing", version = "11.3" }
databinding = { group = "org.eclipse.platform", name = "org.eclipse.core.databinding", version = "1.13.100" }
datePicker = { group = "com.github.lgooddatepicker", name = "LGoodDatePicker", version = "11.2.1" }
swingx = { group = "org.swinglabs", name = "swingx", version = "1.6.1" }
jackson-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version = "2.16.1" }
kotlinpoet-javapoet = { group = "com.squareup", name = "kotlinpoet-javapoet", version = "1.16.0" }

batik-dom = { group = "org.apache.xmlgraphics", name = "batik-dom", version = "1.17" }
batik-svggen = { group = "org.apache.xmlgraphics", name = "batik-svggen", version = "1.17" }
batik-codec = { group = "org.apache.xmlgraphics", name = "batik-codec", version = "1.17" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.5" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version = "12.1.0" }
ben-manes-versions = { id = "com.github.ben-manes.versions", version = "0.51.0" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.10" }
vaniktech-publish = { id = "com.vanniktech.maven.publish", version = "0.27.0" }
